In [5]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from xgboost import plot_importance
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, precision_score, f1_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn import preprocessing
from imblearn.over_sampling import SMOTE, RandomOverSampler, BorderlineSMOTE, ADASYN
from imblearn.combine import SMOTEENN, SMOTETomek 
from imblearn.under_sampling import NearMiss, RandomUnderSampler, CondensedNearestNeighbour, OneSidedSelection, TomekLinks, ClusterCentroids
# from lightgbm import LGBMClassifier


import os
import sys
sys.path.append(os.pardir)
import graphviz
import mglearn
import xgboost as xgb
import seaborn as sns
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

In [6]:
df = pd.read_csv('C:/Users/aischool/heart_2020_cleaned.csv')
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6.0,Yes,No,No
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,No,Yes,Very good,5.0,Yes,No,No
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,No,Yes,Good,6.0,No,No,No
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,No,Good,12.0,No,No,No
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,No,Yes,Good,8.0,No,No,No

In [7]:
one_dr_encoder = OrdinalEncoder()

In [8]:
age_df = df[['AgeCategory']]
age_df

        AgeCategory
0             55-59
1       80 or older
2             65-69
3             75-79
4             40-44
...             ...
319790        60-64
319791        35-39
319792        45-49
319793        25-29
319794  80 or older

[319795 rows x 1 columns]

In [9]:
df_age = one_dr_encoder.fit_transform(age_df)
o_e_df= pd.DataFrame(df_age, columns=['Age'])
o_e_df.value_counts()

Age
9.0     34151
8.0     33686
10.0    31065
7.0     29757
6.0     25382
12.0    24153
5.0     21791
11.0    21482
0.0     21064
4.0     21006
3.0     20550
2.0     18753
1.0     16955
dtype: int64

In [10]:
df_diab= df[['Diabetic']]
df_diab.value_counts()

Diabetic
No                         269653
Yes                         40802
No, borderline diabetes      6781
Yes (during pregnancy)       2559
dtype: int64

In [11]:
o_e_di = one_dr_encoder.fit_transform(df_diab)
di = pd.DataFrame(o_e_di, columns = ['Diabetic'])
di.value_counts()

Diabetic
0.0         269653
2.0          40802
1.0           6781
3.0           2559
dtype: int64

In [12]:
di = di.replace({'Diabetic': 1}, 0)
di = di.replace({'Diabetic': 2}, 1)
di = di.replace({'Diabetic': 3}, 1)
di

        Diabetic
0            1.0
1            0.0
2            1.0
3            0.0
4            0.0
...          ...
319790       1.0
319791       0.0
319792       0.0
319793       0.0
319794       0.0

[319795 rows x 1 columns]

In [13]:
X_df = df.drop(columns=['Diabetic'],axis=1)
X_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,No,Fair,6.0,Yes,No,No
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,Yes,Very good,5.0,Yes,No,No
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,Yes,Good,6.0,No,No,No
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,Good,12.0,No,No,No
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,Yes,Good,8.0,No,No,No

In [14]:
X_df = pd.concat([X_df, o_e_df, di], axis=1, join='inner') 
X_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,Age,Diabetic
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Very good,5.0,Yes,No,Yes,7.0,1.0
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,Yes,Very good,7.0,No,No,No,12.0,0.0
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Fair,8.0,Yes,No,No,9.0,1.0
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,Good,6.0,No,No,Yes,11.0,0.0
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,Yes,Very good,8.0,No,No,No,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,No,Fair,6.0,Yes,No,No,8.0,1.0
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,Yes,Very good,5.0,Yes,No,No,3.0,0.0
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,Yes,Good,6.0,No,No,No,5.0,0.0
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,Good,12.0,No,No,No,1.0,0.0
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,Yes,Good,8.0,No,No,No,12.0,0.0

In [15]:
bins = [-1,1,3,5,7,13]
group_name = [1,2,3,4,5]
categorise = pd.cut(X_df['Age'],bins,labels=group_name)
X_df['Age']=categorise
X_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,Age,Diabetic
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Very good,5.0,Yes,No,Yes,4,1.0
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,Yes,Very good,7.0,No,No,No,5,0.0
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Fair,8.0,Yes,No,No,5,1.0
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,Good,6.0,No,No,Yes,5,0.0
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,Yes,Very good,8.0,No,No,No,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,No,Fair,6.0,Yes,No,No,5,1.0
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,Yes,Very good,5.0,Yes,No,No,2,0.0
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,Yes,Good,6.0,No,No,No,3,0.0
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,Good,12.0,No,No,No,1,0.0
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,Yes,Good,8.0,No,No,No,5,0.0

In [16]:
X1_df = X_df.astype({'Age':'int64'})

In [17]:
X1_df_1 = X1_df.drop(columns=['AgeCategory'],axis=1)
X1_df_1

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,Age,Diabetic
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,White,Yes,Very good,5.0,Yes,No,Yes,4,1.0
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,White,Yes,Very good,7.0,No,No,No,5,0.0
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,White,Yes,Fair,8.0,Yes,No,No,5,1.0
3,No,24.21,No,No,No,0.0,0.0,No,Female,White,No,Good,6.0,No,No,Yes,5,0.0
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,White,Yes,Very good,8.0,No,No,No,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,Hispanic,No,Fair,6.0,Yes,No,No,5,1.0
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,Hispanic,Yes,Very good,5.0,Yes,No,No,2,0.0
319792,No,24.24,No,No,No,0.0,0.0,No,Female,Hispanic,Yes,Good,6.0,No,No,No,3,0.0
319793,No,32.81,No,No,No,0.0,0.0,No,Female,Hispanic,No,Good,12.0,No,No,No,1,0.0
319794,No,46.56,No,No,No,0.0,0.0,No,Female,Hispanic,Yes,Good,8.0,No,No,No,5,0.0

In [18]:
X1_df_1 = X1_df_1.drop(columns=['Race','GenHealth','SkinCancer','PhysicalHealth','MentalHealth'],axis=1)
X1_df_1

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age,Diabetic
0,No,16.60,Yes,No,No,No,Female,Yes,5.0,Yes,No,4,1.0
1,No,20.34,No,No,Yes,No,Female,Yes,7.0,No,No,5,0.0
2,No,26.58,Yes,No,No,No,Male,Yes,8.0,Yes,No,5,1.0
3,No,24.21,No,No,No,No,Female,No,6.0,No,No,5,0.0
4,No,23.71,No,No,No,Yes,Female,Yes,8.0,No,No,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,Yes,Male,No,6.0,Yes,No,5,1.0
319791,No,29.84,Yes,No,No,No,Male,Yes,5.0,Yes,No,2,0.0
319792,No,24.24,No,No,No,No,Female,Yes,6.0,No,No,3,0.0
319793,No,32.81,No,No,No,No,Female,No,12.0,No,No,1,0.0
319794,No,46.56,No,No,No,No,Female,Yes,8.0,No,No,5,0.0

In [19]:
X1_df_1['HeartDisease'] = [1 if each == 'Yes' else 0 for each in X1_df_1['HeartDisease']]

In [20]:
X1_df_1['Smoking'] = [1 if each == 'Yes' else 0 for each in X1_df_1['Smoking']]

In [21]:
X1_df_1['AlcoholDrinking'] = [1 if each == 'Yes' else 0 for each in X1_df_1['AlcoholDrinking']]

In [22]:
X1_df_1['Stroke'] = [1 if each == 'Yes' else 0 for each in X1_df_1['Stroke']]

In [23]:
X1_df_1['Sex'] = [1 if each == 'Male' else 0 for each in X1_df_1['Sex']]

In [24]:
X1_df_1['PhysicalActivity'] = [1 if each == 'Yes' else 0 for each in X1_df_1['PhysicalActivity']]

In [25]:
X1_df_1['DiffWalking'] = [1 if each == 'Yes' else 0 for each in X1_df_1['DiffWalking']]

In [26]:
X1_df_1['Asthma'] = [1 if each == 'Yes' else 0 for each in X1_df_1['Asthma']]

In [27]:
X1_df_1['KidneyDisease'] = [1 if each == 'Yes' else 0 for each in X1_df_1['KidneyDisease']]

In [28]:
X1_df_1

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age,Diabetic
0,0,16.60,1,0,0,0,0,1,5.0,1,0,4,1.0
1,0,20.34,0,0,1,0,0,1,7.0,0,0,5,0.0
2,0,26.58,1,0,0,0,1,1,8.0,1,0,5,1.0
3,0,24.21,0,0,0,0,0,0,6.0,0,0,5,0.0
4,0,23.71,0,0,0,1,0,1,8.0,0,0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,1,1,0,6.0,1,0,5,1.0
319791,0,29.84,1,0,0,0,1,1,5.0,1,0,2,0.0
319792,0,24.24,0,0,0,0,0,1,6.0,0,0,3,0.0
319793,0,32.81,0,0,0,0,0,0,12.0,0,0,1,0.0
319794,0,46.56,0,0,0,0,0,1,8.0,0,0,5,0.0

In [29]:
y_target = X1_df_1['Diabetic']
y_target.value_counts()

0.0    276434
1.0     43361
Name: Diabetic, dtype: int64

In [30]:
X1_df_1 = X1_df_1.drop(columns=['Diabetic'],axis=1)
X1_df_1

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age
0,0,16.60,1,0,0,0,0,1,5.0,1,0,4
1,0,20.34,0,0,1,0,0,1,7.0,0,0,5
2,0,26.58,1,0,0,0,1,1,8.0,1,0,5
3,0,24.21,0,0,0,0,0,0,6.0,0,0,5
4,0,23.71,0,0,0,1,0,1,8.0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,1,1,0,6.0,1,0,5
319791,0,29.84,1,0,0,0,1,1,5.0,1,0,2
319792,0,24.24,0,0,0,0,0,1,6.0,0,0,3
319793,0,32.81,0,0,0,0,0,0,12.0,0,0,1
319794,0,46.56,0,0,0,0,0,1,8.0,0,0,5

In [31]:
bins  = [0,18.50,24.99,29.99,34.99,39.99,99]
group_names = [1,2,3,4,5,6]   # bin a < 구간 <= b
categorise = pd.cut(X1_df_1['BMI'],bins,labels=group_names)
X1_df_1["BMI"]= categorise
X1_df_1['BMI'].value_counts()   # 1: 저체중 2:정상 3:과체중 4: 1단계비만 5: 2단계 비만 6: 고도비만

3    114512
2     97327
4     61345
5     25112
6     16385
1      5114
Name: BMI, dtype: int64

In [32]:
X1_df_1 = X1_df_1.astype({'BMI':'float64'})

In [33]:
train_df = X1_df_1
train_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age
0,0,1.0,1,0,0,0,0,1,5.0,1,0,4
1,0,2.0,0,0,1,0,0,1,7.0,0,0,5
2,0,3.0,1,0,0,0,1,1,8.0,1,0,5
3,0,2.0,0,0,0,0,0,0,6.0,0,0,5
4,0,2.0,0,0,0,1,0,1,8.0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,3.0,1,0,0,1,1,0,6.0,1,0,5
319791,0,3.0,1,0,0,0,1,1,5.0,1,0,2
319792,0,2.0,0,0,0,0,0,1,6.0,0,0,3
319793,0,4.0,0,0,0,0,0,0,12.0,0,0,1
319794,0,6.0,0,0,0,0,0,1,8.0,0,0,5

In [34]:
train_df = train_df.astype({'SleepTime':'float64'})

In [35]:
X = train_df

In [36]:
y = y_target

In [37]:
smoenn = SMOTEENN(random_state=0)
X, y = smoenn.fit_resample(X,y)

In [38]:
diabetic = pd.concat([X,y], axis=1, join='inner')
diabetic = pd.DataFrame.from_dict(diabetic)

In [39]:
diabetic.to_csv("C:/Users/aischool/heart_2020_cleaned.csv", header=True, index=False)

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.05, stratify=y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((228649, 12), (12035, 12), (228649,), (12035,))

In [41]:
def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
#     roc_auc = roc_auc(y_test, pred_proba)
    print('오차행렬')
    print(confusion)
    print('정확도:{0:.4f},정밀도:{1:.4f},재현율:{2:.4f},F1{3:.4f}'.format(accuracy, precision, recall, f1))

In [42]:
def get_model_train_eval(model, ftr_train = None, ftr_test=None, tgt_train=None, tgt_test=None):
    model.fit(ftr_train, tgt_train)
    pred = model.predict(ftr_test)
    pred_proba = model.predict_proba(ftr_test)[:, 1]
    get_clf_eval(tgt_test, pred, pred_proba)

In [43]:
xgb_model = XGBClassifier(base_score = 0.5,
                          n_estimators = 300,
                          learning_rate = 0.1,
                          max_depth = 10,
                          scale_pos_weight= 3,
                          reg_lambda=400,
                          n_jobs=-1,
                          subsample=1,
                          colsample_bytree=1)
get_model_train_eval(xgb_model, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

오차행렬
[[9050  622]
 [ 305 2058]]
정확도:0.9230,정밀도:0.7679,재현율:0.8709,F10.8162

In [44]:
xgb_model.score(X_train, y_train), xgb_model.score(X_test, y_test)

(0.9240276581135277, 0.9229746572496884)