In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from xgboost import plot_importance
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import GridSearchCV
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, precision_score, f1_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn import preprocessing
from sklearn.cluster import KMeans
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import * 
from imblearn.under_sampling import *
# from lightgbm import LGBMClassifier

import seaborn as sns
import os
import sys
sys.path.append(os.pardir)
import graphviz
import mglearn
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

In [3]:
df = pd.read_csv('C:/Users/aischool/heart_2020_cleaned.csv')
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6.0,Yes,No,No
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,No,Yes,Very good,5.0,Yes,No,No
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,No,Yes,Good,6.0,No,No,No
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,No,Good,12.0,No,No,No
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,No,Yes,Good,8.0,No,No,No

In [4]:
df = df.drop(columns=['PhysicalHealth','MentalHealth','Race','GenHealth','SkinCancer'],axis=1)
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,AgeCategory,Diabetic,PhysicalActivity,SleepTime,Asthma,KidneyDisease
0,No,16.60,Yes,No,No,No,Female,55-59,Yes,Yes,5.0,Yes,No
1,No,20.34,No,No,Yes,No,Female,80 or older,No,Yes,7.0,No,No
2,No,26.58,Yes,No,No,No,Male,65-69,Yes,Yes,8.0,Yes,No
3,No,24.21,No,No,No,No,Female,75-79,No,No,6.0,No,No
4,No,23.71,No,No,No,Yes,Female,40-44,No,Yes,8.0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,Yes,Male,60-64,Yes,No,6.0,Yes,No
319791,No,29.84,Yes,No,No,No,Male,35-39,No,Yes,5.0,Yes,No
319792,No,24.24,No,No,No,No,Female,45-49,No,Yes,6.0,No,No
319793,No,32.81,No,No,No,No,Female,25-29,No,No,12.0,No,No
319794,No,46.56,No,No,No,No,Female,80 or older,No,Yes,8.0,No,No

In [5]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 223212 entries, 0 to 319794
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      223212 non-null  object
 1   BMI               223212 non-null  float64
 2   Smoking           223212 non-null  object
 3   AlcoholDrinking   223212 non-null  object
 4   Stroke            223212 non-null  object
 5   DiffWalking       223212 non-null  object
 6   Sex               223212 non-null  object
 7   AgeCategory       223212 non-null  object
 8   Diabetic          223212 non-null  object
 9   PhysicalActivity  223212 non-null  object
 10  SleepTime         223212 non-null  float64
 11  Asthma            223212 non-null  object
 12  KidneyDisease     223212 non-null  object
dtypes: float64(2), object(11)
memory usage: 23.8+ MB

In [8]:
df = df[(df['BMI']<80) ]