# 아시아_피부암

In [1]:
# 패키지 라이브러리 불러오기
from sklearn.datasets import load_iris
from sklearn.datasets import load_breast_cancer
from sklearn.datasets import make_moons
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from xgboost import plot_importance
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score, confusion_matrix, precision_score, f1_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
# from category_encoders import OrdinalEncoder
# from category_encoders import OneHotEncoder
from sklearn import preprocessing
from imblearn.over_sampling import SMOTE

import os
import sys
sys.path.append(os.pardir)
import graphviz
import mglearn
import xgboost as xgb
import seaborn as sns
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

In [2]:
# pd.set_option('display.max_columns',None)
# pd.set_option('display.max_rows',None)

### 데이터 불러오기

In [3]:
# 데이터 준비
df = pd.read_csv('C:/Users/gjaischool/CHU/itIT/heart_2020_cleaned.csv')
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6.0,Yes,No,No
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,No,Yes,Very good,5.0,Yes,No,No
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,No,Yes,Good,6.0,No,No,No
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,No,Good,12.0,No,No,No
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,No,Yes,Good,8.0,No,No,No

### 아시아인 데이터만 출력하기 라인번호 재설정
- 인종에서 Asian인만 빼서 설정

In [4]:
df_asian = df[df['Race']=='Asian']
df_asian = df_asian.reset_index(drop=True)
df_asian

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,40.00,No,No,No,0.0,0.0,No,Male,60-64,Asian,Yes,No,Good,6.0,No,No,No
1,No,17.71,No,No,No,0.0,10.0,No,Female,65-69,Asian,No,Yes,Good,6.0,No,No,No
2,No,25.80,No,No,No,0.0,0.0,No,Male,50-54,Asian,No,No,Very good,7.0,No,No,No
3,No,25.61,No,No,No,0.0,0.0,No,Female,60-64,Asian,Yes,Yes,Good,7.0,No,No,No
4,Yes,20.36,No,No,No,10.0,0.0,Yes,Male,70-74,Asian,No,No,Fair,5.0,Yes,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8063,No,25.61,No,No,No,30.0,0.0,No,Female,60-64,Asian,No,Yes,Poor,6.0,No,Yes,No
8064,No,23.83,No,No,No,0.0,0.0,No,Female,70-74,Asian,No,No,Very good,8.0,No,No,No
8065,No,29.39,No,No,No,0.0,0.0,No,Male,65-69,Asian,No,Yes,Fair,7.0,No,No,No
8066,No,24.03,No,Yes,No,0.0,20.0,No,Female,18-24,Asian,No,Yes,Excellent,8.0,Yes,No,No
8067,No,27.44,No,No,No,0.0,0.0,No,Female,55-59,Asian,No,Yes,Excellent,7.0,No,No,No

In [5]:
df_asian.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   HeartDisease      8068 non-null   object
 1   BMI               8068 non-null   float64
 2   Smoking           8068 non-null   object
 3   AlcoholDrinking   8068 non-null   object
 4   Stroke            8068 non-null   object
 5   PhysicalHealth    8068 non-null   float64
 6   MentalHealth      8068 non-null   float64
 7   DiffWalking       8068 non-null   object
 8   Sex               8068 non-null   object
 9   AgeCategory       8068 non-null   object
 10  Race              8068 non-null   object
 11  Diabetic          8068 non-null   object
 12  PhysicalActivity  8068 non-null   object
 13  GenHealth         8068 non-null   object
 14  SleepTime         8068 non-null   float64
 15  Asthma            8068 non-null   object
 16  KidneyDisease     8068 non-null   object
 17  SkinCancer        8068 non-null   object
dtypes: float64(4), object(14)
memory usage: 1.1+ MB

### 범주형값을 수치값으로 변환(AgeCategory, Diabetic)
- OrfinalEncoder으로 라베링 실시
- AgeCategory, Diabetic값 OrdinalEncoder로 변환

In [6]:
one_dr_encoder = OrdinalEncoder()

In [7]:
age_df = df_asian[['AgeCategory']]
age_df

     AgeCategory
0          60-64
1          65-69
2          50-54
3          60-64
4          70-74
...          ...
8063       60-64
8064       70-74
8065       65-69
8066       18-24
8067       55-59

[8068 rows x 1 columns]

In [8]:
age_df['AgeCategory'].value_counts()

18-24          1148
25-29           850
30-34           786
35-39           783
40-44           682
45-49           635
50-54           625
60-64           581
55-59           532
65-69           489
70-74           435
80 or older     274
75-79           248
Name: AgeCategory, dtype: int64

In [9]:
df_age = one_dr_encoder.fit_transform(age_df)
o_e_df= pd.DataFrame(df_age, columns=['Age'])
o_e_df.value_counts()

Age
0.0     1148
1.0      850
2.0      786
3.0      783
4.0      682
5.0      635
6.0      625
8.0      581
7.0      532
9.0      489
10.0     435
12.0     274
11.0     248
dtype: int64

### Diabetic 값 라벨링

In [10]:
df_diab= df_asian[['Diabetic']]
df_diab.value_counts()

Diabetic
No                         6850
Yes                         782
No, borderline diabetes     339
Yes (during pregnancy)       97
dtype: int64

In [11]:
o_e_di = one_dr_encoder.fit_transform(df_diab)
di = pd.DataFrame(o_e_di, columns = ['Diabetic'])
di.value_counts()

Diabetic
0.0         6850
2.0          782
1.0          339
3.0           97
dtype: int64

In [12]:
di = di.replace({'Diabetic': 1}, 0)
di = di.replace({'Diabetic': 2}, 1)
di = di.replace({'Diabetic': 3}, 1)
di

      Diabetic
0          1.0
1          0.0
2          0.0
3          1.0
4          0.0
...        ...
8063       0.0
8064       0.0
8065       0.0
8066       0.0
8067       0.0

[8068 rows x 1 columns]

### Diabetic 값 제거

In [13]:
X_df = df.drop(columns=['Diabetic'],axis=1)
X_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,No,Fair,6.0,Yes,No,No
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,Yes,Very good,5.0,Yes,No,No
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,Yes,Good,6.0,No,No,No
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,Good,12.0,No,No,No
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,Yes,Good,8.0,No,No,No

### 변환했던 값 concat으로 합치기
- o_e_df : AgeCategory
- di : Diabetic

In [14]:
X_df = pd.concat([X_df, o_e_df,di], axis=1, join='inner') 
X_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,Age,Diabetic
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Very good,5.0,Yes,No,Yes,8.0,1.0
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,Yes,Very good,7.0,No,No,No,9.0,0.0
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Fair,8.0,Yes,No,No,6.0,0.0
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,Good,6.0,No,No,Yes,8.0,1.0
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,Yes,Very good,8.0,No,No,No,10.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8063,No,33.00,Yes,No,No,5.0,3.0,Yes,Male,80 or older,White,No,Fair,7.0,No,No,Yes,8.0,0.0
8064,No,23.01,No,No,No,0.0,0.0,No,Male,80 or older,Black,Yes,Good,8.0,No,Yes,No,10.0,0.0
8065,Yes,22.53,Yes,No,No,0.0,0.0,No,Male,70-74,White,Yes,Good,8.0,No,No,Yes,9.0,0.0
8066,No,29.29,Yes,No,No,0.0,0.0,No,Male,80 or older,White,Yes,Very good,8.0,No,No,No,0.0,0.0
8067,No,24.87,No,Yes,No,0.0,3.0,No,Female,70-74,White,Yes,Very good,7.0,No,No,No,7.0,0.0

### Age구간을 구분하여 컬럼 지정

In [15]:
bins = [-1,1,3,5,7,13]
group_name = [1,2,3,4,5]
categorise = pd.cut(X_df['Age'],bins,labels=group_name)
X_df['Age']=categorise
X_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,Age,Diabetic
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Very good,5.0,Yes,No,Yes,5,1.0
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,Yes,Very good,7.0,No,No,No,5,0.0
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Fair,8.0,Yes,No,No,4,0.0
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,Good,6.0,No,No,Yes,5,1.0
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,Yes,Very good,8.0,No,No,No,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8063,No,33.00,Yes,No,No,5.0,3.0,Yes,Male,80 or older,White,No,Fair,7.0,No,No,Yes,5,0.0
8064,No,23.01,No,No,No,0.0,0.0,No,Male,80 or older,Black,Yes,Good,8.0,No,Yes,No,5,0.0
8065,Yes,22.53,Yes,No,No,0.0,0.0,No,Male,70-74,White,Yes,Good,8.0,No,No,Yes,5,0.0
8066,No,29.29,Yes,No,No,0.0,0.0,No,Male,80 or older,White,Yes,Very good,8.0,No,No,No,1,0.0
8067,No,24.87,No,Yes,No,0.0,3.0,No,Female,70-74,White,Yes,Very good,7.0,No,No,No,4,0.0

### Age타입 변경 : int64, 불필요한 컬럼 drop ('AgeCategory','PhysicalHealth','MentalHealth','Race','GenHealth')

In [16]:
X1_df = X_df.astype({'Age':'int64'})

In [17]:
X1_df_1 = X1_df.drop(columns=['AlcoholDrinking','AgeCategory','PhysicalHealth','MentalHealth','Race','GenHealth'],axis=1)
X1_df_1

,HeartDisease,BMI,Smoking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,SkinCancer,Age,Diabetic
0,No,16.60,Yes,No,No,Female,Yes,5.0,Yes,No,Yes,5,1.0
1,No,20.34,No,Yes,No,Female,Yes,7.0,No,No,No,5,0.0
2,No,26.58,Yes,No,No,Male,Yes,8.0,Yes,No,No,4,0.0
3,No,24.21,No,No,No,Female,No,6.0,No,No,Yes,5,1.0
4,No,23.71,No,No,Yes,Female,Yes,8.0,No,No,No,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8063,No,33.00,Yes,No,Yes,Male,No,7.0,No,No,Yes,5,0.0
8064,No,23.01,No,No,No,Male,Yes,8.0,No,Yes,No,5,0.0
8065,Yes,22.53,Yes,No,No,Male,Yes,8.0,No,No,Yes,5,0.0
8066,No,29.29,Yes,No,No,Male,Yes,8.0,No,No,No,1,0.0
8067,No,24.87,No,No,No,Female,Yes,7.0,No,No,No,4,0.0

### 인코딩 작업
- 축약 if문 사용

In [18]:
X1_df_1['HeartDisease'] = [1 if each == 'Yes' else 0 for each in X1_df_1['HeartDisease']]

In [19]:
X1_df_1['Smoking'] = [1 if each == 'Yes' else 0 for each in X1_df_1['Smoking']]

In [20]:
X1_df_1['Stroke'] = [1 if each == 'Yes' else 0 for each in X1_df_1['Stroke']]

In [21]:
X1_df_1['Sex'] = [1 if each == 'Male' else 0 for each in X1_df_1['Sex']]

In [22]:
X1_df_1['PhysicalActivity'] = [1 if each == 'Yes' else 0 for each in X1_df_1['PhysicalActivity']]

In [23]:
X1_df_1['DiffWalking'] = [1 if each == 'Yes' else 0 for each in X1_df_1['DiffWalking']]

In [24]:
X1_df_1['Asthma'] = [1 if each == 'Yes' else 0 for each in X1_df_1['Asthma']]

In [25]:
X1_df_1['KidneyDisease'] = [1 if each == 'Yes' else 0 for each in X1_df_1['KidneyDisease']]

In [26]:
X1_df_1['SkinCancer'] = [1 if each == 'Yes' else 0 for each in X1_df_1['SkinCancer']]

In [27]:
X1_df_1

,HeartDisease,BMI,Smoking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,SkinCancer,Age,Diabetic
0,0,16.60,1,0,0,0,1,5.0,1,0,1,5,1.0
1,0,20.34,0,1,0,0,1,7.0,0,0,0,5,0.0
2,0,26.58,1,0,0,1,1,8.0,1,0,0,4,0.0
3,0,24.21,0,0,0,0,0,6.0,0,0,1,5,1.0
4,0,23.71,0,0,1,0,1,8.0,0,0,0,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8063,0,33.00,1,0,1,1,0,7.0,0,0,1,5,0.0
8064,0,23.01,0,0,0,1,1,8.0,0,1,0,5,0.0
8065,1,22.53,1,0,0,1,1,8.0,0,0,1,5,0.0
8066,0,29.29,1,0,0,1,1,8.0,0,0,0,1,0.0
8067,0,24.87,0,0,0,0,1,7.0,0,0,0,4,0.0

### Y타겟(SkinCanert)설정 및 제거

In [28]:
y_target = X1_df_1['SkinCancer']
y_target.value_counts()

0    7180
1     888
Name: SkinCancer, dtype: int64

In [29]:
X1_df_1 = X1_df_1.drop(columns=['SkinCancer'],axis=1)
X1_df_1

,HeartDisease,BMI,Smoking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age,Diabetic
0,0,16.60,1,0,0,0,1,5.0,1,0,5,1.0
1,0,20.34,0,1,0,0,1,7.0,0,0,5,0.0
2,0,26.58,1,0,0,1,1,8.0,1,0,4,0.0
3,0,24.21,0,0,0,0,0,6.0,0,0,5,1.0
4,0,23.71,0,0,1,0,1,8.0,0,0,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8063,0,33.00,1,0,1,1,0,7.0,0,0,5,0.0
8064,0,23.01,0,0,0,1,1,8.0,0,1,5,0.0
8065,1,22.53,1,0,0,1,1,8.0,0,0,5,0.0
8066,0,29.29,1,0,0,1,1,8.0,0,0,1,0.0
8067,0,24.87,0,0,0,0,1,7.0,0,0,4,0.0

### 구간값을 실수값으로 구분하여 레이블 저장 및 타입 변경 : 원래 -object / 변경타입 - int
- 0 ~ 18.50 : 저체중 / groupnames = 1
- 18.50 ~ 24.99 : 정상 / groupnames = 2
- 25.00 ~ 29.99 : 과체중 / groupnames = 3
- 30.00 ~ 34.99 : 1단계 비만 / groupnames = 4
- 35.00 ~ 39.99 : 2단계 비만 / groupnames = 5
- 40 ~ : 고도비만 / groupnames = 6

In [30]:
bins  = [0,18.50,24.99,29.99,34.99,39.99,99]
group_names = [1,2,3,4,5,6]   # bin a < 구간 <= b
categorise = pd.cut(X1_df_1['BMI'],bins,labels=group_names)
X1_df_1["BMI"]= categorise
X1_df_1 # 1: 저체중 2:정상 3:과체중 4: 1단계비만 5: 2단계 비만 6: 고도비만

,HeartDisease,BMI,Smoking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age,Diabetic
0,0,1,1,0,0,0,1,5.0,1,0,5,1.0
1,0,2,0,1,0,0,1,7.0,0,0,5,0.0
2,0,3,1,0,0,1,1,8.0,1,0,4,0.0
3,0,3,0,0,0,0,0,6.0,0,0,5,1.0
4,0,2,0,0,1,0,1,8.0,0,0,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8063,0,4,1,0,1,1,0,7.0,0,0,5,0.0
8064,0,2,0,0,0,1,1,8.0,0,1,5,0.0
8065,1,2,1,0,0,1,1,8.0,0,0,5,0.0
8066,0,4,1,0,0,1,1,8.0,0,0,1,0.0
8067,0,3,0,0,0,0,1,7.0,0,0,4,0.0

In [31]:
X1_df_1 = X1_df_1.astype({'BMI':'int64'})

In [32]:
X1_df_1['BMI'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8068 entries, 0 to 8067
Series name: BMI
Non-Null Count  Dtype
--------------  -----
8068 non-null   int64
dtypes: int64(1)
memory usage: 63.2 KB

### 최종데이터

In [33]:
train_df = X1_df_1

In [34]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   HeartDisease      8068 non-null   int64
 1   BMI               8068 non-null   int64
 2   Smoking           8068 non-null   int64
 3   Stroke            8068 non-null   int64
 4   DiffWalking       8068 non-null   int64
 5   Sex               8068 non-null   int64
 6   PhysicalActivity  8068 non-null   int64
 7   SleepTime         8068 non-null   float64
 8   Asthma            8068 non-null   int64
 9   KidneyDisease     8068 non-null   int64
 10  Age               8068 non-null   int64
 11  Diabetic          8068 non-null   float64
dtypes: float64(2), int64(10)
memory usage: 756.5 KB

### 학습 및 정확도 확인, 변수 중요도 확인

In [35]:
X = train_df

In [36]:
y = y_target

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.05, stratify=y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((7664, 12), (404, 12), (7664,), (404,))

In [38]:
# X_train_valid, X_test, y_train_valid, y_test = train_test_split(X, y, test_size=0.05, stratify=y)
# X_train, X_train_valid, y_train, y_train_valid = train_test_split(X_train_valid, y_train_valid, test_size=0.05, stratify=y_train_valid)

In [39]:
# xgbr_all = XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, objective='reg:squarederror', radom_state=2021)
# xgbr_all.fit(X_train, y_train)
# pred = xgbr_all.predict(X_train_valid)

# rmse = np.sqrt(mean_squared_error(y_train_valid, pred))

# fig, ax = plt.subplots(figsize=(10,10))
# plot_importance(xgbr_all, ax=ax)

### RandomForestRegressor

In [40]:
rf_model = RandomForestRegressor()
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)
rf_model.score(X_train, y_train)
# rf_model.score(y_test, y_pred)
# accuracy_score(rf_model, y_test)

0.45237656772399404

### LogisticRegression

In [41]:
lr_model = LogisticRegression(max_iter=100000)
lr_model.fit(X_train, y_train)
pred_lr = lr_model.predict(X_test)
accuracy_score(pred_lr, y_test)

0.8910891089108911

### DecisiontreeClassifier

In [42]:
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
pred_dt = dt_model.predict(X_test)
accuracy_score(pred_dt, y_test)

0.8391089108910891

### KNN

In [43]:
knn_model = KNeighborsClassifier(n_neighbors=10, metric='euclidean', weights='distance')
knn_model.fit(X_train, y_train)
pred_knn = knn_model.predict(X_test)
accuracy_score(pred_knn, y_test)

0.8737623762376238

### GridSearchCV
- LogisticRegression, 교차검증하여 파라미터 값 설정
- RandomForestClassifier, 교차검증하여 파라미터 값 설정

In [44]:
lr_model_1 = LogisticRegression(C=5, penalty='l2', solver='lbfgs')

# lr_grid = {'solver':['liblinear', 'lbfgs'],
#     'penalty':['l1', 'l2'],
#     'C':[0.01, 0.1, 1, 5, 10 ]
# }
# lr_res = GridSearchCV(estimator = lr_model_1,
#                      param_grid=lr_grid,
#                      n_jobs= -1)

lr_model_1.fit(X_train, y_train)

lr_model_1.score(X_test, y_test)

0.8910891089108911

In [45]:
rf_model = RandomForestClassifier(n_estimators=60,max_depth=10, max_features='auto', min_samples_split=3)

# rf_grid = {
#     'n_estimators': [20,40,60,80],
#     'max_depth': [5,10,15,20],
#     'min_samples_split': [0.5, 1, 1.5, 3],
#     'max_features': ['auto', 'sqrt'],
# }
# rf_res = GridSearchCV(estimator=rf_model,
#                      param_grid=rf_grid,
#                      n_jobs= -1,
#                      cv=5)
rf_model.fit(X_train,y_train)
rf_model.score(X_train, y_train),rf_model.score(X_test, y_test)

C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\ensemble\_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(

(0.8975730688935282, 0.8935643564356436)